---
version: '3.7' 
services:
  convert:
    build: 
      context: .
    environment:
      #BASE: '/pub'
      SRC: "cc3a6568-a9c9-480d-b340-9f6192421489"
      NAME: "My New Compressed Disk Image"
      DISTRO: "centos"
      COMPAT: 1.1
      IMG_ORIG_USER: "root"
      INPUT_FORMAT: qcow2
      OUTPUT_FORMAT: qcow2
    volumes: 
      - ./openrc.sh:/openrc.sh
      - pub:/pub
volumes:
  pub: {} 
